name: Release

on:
  push:
    tags: v[1-9]+.[0-9]+.[0-9]+
    branches: master

jobs:

  linux-windows-build:
    name: Linux & Windows Build
    if: startsWith( github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:

    - name: Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16'
    
    - name: OS Packages 
      run: |
        sudo apt-get update --fix-missing && sudo apt-get -y install \
        git build-essential zlib1g zlib1g-dev wget zip unzip \
        mingw-w64 binutils-mingw-w64 g++-mingw-w64 gcc-multilib

    - name: Protoc
      env:
        PROTOC_VER: 3.11.4
      run: |
        wget -O protoc-${PROTOC_VER}-linux-x86_64.zip https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VER}/protoc-${PROTOC_VER}-linux-x86_64.zip \
        && unzip protoc-${PROTOC_VER}-linux-x86_64.zip \
        && sudo cp -vv ./bin/protoc /usr/local/bin/protoc

    - name: Protoc-gen-go
      env:
        PROTOC_GEN_GO_VER: 1.3.5
      run: |
        wget -O protoc-gen-go.tar.gz https://github.com/golang/protobuf/archive/v${PROTOC_GEN_GO_VER}.tar.gz \
        && tar xvf protoc-gen-go.tar.gz \
        && cd protobuf-${PROTOC_GEN_GO_VER} \
        && make install

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Git Fetch Tags
      run: git fetch --prune --unshallow --tags -f

    - name: Go Assets
      run: ./go-assets.sh
    
    - name: Remove Vendor
      run: rm -rf ./vendor/

    - name: Make
      run: export PATH=/home/runner/go/bin/:$PATH && make linux
  
    - name: Linux Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: ./sliver-*

    - name: Make Windows
      run: export PATH=/home/runner/go/bin/:$PATH && make windows

    - name: Windows Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path:  ./sliver-*

  macos-build:
    name: MacOS Build
    if: startsWith( github.ref, 'refs/tags/v')
    runs-on: macos-latest
    steps:

    - name: Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16'

    - name: Mingw
      run: brew install mingw-w64

    - name: Protoc
      env:
        PROTOC_VER: 3.11.4
      run: |
        wget -O protoc-${PROTOC_VER}-osx-x86_64.zip https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VER}/protoc-${PROTOC_VER}-osx-x86_64.zip \
        && unzip protoc-${PROTOC_VER}-osx-x86_64.zip \
        && sudo cp -vv ./bin/protoc /usr/local/bin/protoc

    - name: Protoc-gen-go
      env:
        PROTOC_GEN_GO_VER: 1.3.5
      run: |
        wget -O protoc-gen-go.tar.gz https://github.com/golang/protobuf/archive/v${PROTOC_GEN_GO_VER}.tar.gz \
        && tar xvf protoc-gen-go.tar.gz \
        && cd protobuf-${PROTOC_GEN_GO_VER} \
        && make install

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Git Fetch Tags
      run: git fetch --prune --unshallow --tags -f

    - name: Go Assets
      run: ./go-assets.sh

    - name: Remove Vendor
      run: rm -rf ./vendor/

    - name: Make AMD64
      run: make macos
    
    # - name: Make ARM64
    #   run: make macos-arm64

    - name: MacOS Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: macos
        path: ./sliver-*

  tagged-release:

    needs: [linux-windows-build, macos-build]

    name: "Tagged Release"
    if: startsWith( github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
    - run: mkdir -p ./release && mkdir -p ./artifacts
    - uses: actions/download-artifact@v2
      with:
        path: ./artifacts

    - id: install-secret-key
      name: GPG Key(s)
      run: |
        cat <(echo -e "${{ secrets.SLIVER_GPG }}") | gpg --batch --import
        gpg --list-secret-keys --keyid-format LONG

    # Linux
    - name: Linux AMD64
      run: |
        cp ./artifacts/linux/sliver-server ./release/sliver-server_linux-amd64
        cp ./artifacts/linux/sliver-client ./release/sliver-client_linux-amd64
        gpg --default-key 4449039C --output ./release/sliver-server_linux-amd64.sig --detach-sig ./release/sliver-server_linux-amd64
        gpg --default-key 4449039C --output ./release/sliver-client_linux-amd64.sig --detach-sig ./release/sliver-client_linux-amd64

    # Windows
    - name: Windows AMD64
      run: |
        cp ./artifacts/windows/sliver-server.exe ./release/sliver-server_windows-amd64.exe
        cp ./artifacts/windows/sliver-client.exe ./release/sliver-client_windows-amd64.exe
        gpg --default-key 4449039C --output ./release/sliver-server_windows-amd64.exe.sig --detach-sig ./release/sliver-server_windows-amd64.exe
        gpg --default-key 4449039C --output ./release/sliver-client_windows-amd64.exe.sig --detach-sig ./release/sliver-client_windows-amd64.exe

    # MacOS AMD64
    - name: MacOS AMD64
      run: |
        cp ./artifacts/macos/sliver-server ./release/sliver-server_macos-amd64
        cp ./artifacts/macos/sliver-client ./release/sliver-client_macos-amd64
        gpg --default-key 4449039C --output ./release/sliver-server_macos-amd64.sig --detach-sig ./release/sliver-server_macos-amd64
        gpg --default-key 4449039C --output ./release/sliver-client_macos-amd64.sig --detach-sig ./release/sliver-client_macos-amd64

    # MacOS ARM64
    # - name: MacOS ARM64
    #   run: |
    #     cp ./artifacts/macos/sliver-server ./release/sliver-server_macos-arm64
    #     cp ./artifacts/macos/sliver-client ./release/sliver-client_macos-arm64
    #     gpg --default-key 4449039C --output ./release/sliver-server_macos-arm64.sig --detach-sig ./release/sliver-server_macos-arm64
    #     gpg --default-key 4449039C --output ./release/sliver-client_macos-arm64.sig --detach-sig ./release/sliver-client_macos-arm64

    - name: "Publish Release"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          ./release/*
