name: Go
on:
  push:
    branches: 
      - master
      - test/*

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go
    
    - name: OS Packages 
      run: |
        sudo apt-get update --fix-missing && sudo apt-get -y install \
        git build-essential zlib1g zlib1g-dev wget zip unzip 

    - name: Protoc
      env:
        PROTOC_VER: 3.7.1
      run: |
        wget -O protoc-${PROTOC_VER}-linux-x86_64.zip https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VER}/protoc-${PROTOC_VER}-linux-x86_64.zip \
        && unzip protoc-${PROTOC_VER}-linux-x86_64.zip \
        && sudo cp -vv ./bin/protoc /usr/local/bin/protoc

    - name: Protoc-gen-go
      env:
        PROTOC_GEN_GO_VER: 1.3.5
      run: |
        wget -O protoc-gen-go.tar.gz https://github.com/golang/protobuf/archive/v${PROTOC_GEN_GO_VER}.tar.gz \
        && tar xvf protoc-gen-go.tar.gz \
        && cd protobuf-${PROTOC_GEN_GO_VER} \
        && make install

    - name: Packr
      env:
        PACKR_VER: 1.30.1
      run: |
        wget -O packr.tar.gz https://github.com/gobuffalo/packr/archive/v${PACKR_VER}.tar.gz \
        && tar xvf packr.tar.gz \
        && cd packr-${PACKR_VER} \
        && make install

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Go Assets
      run: ./go-assets.sh

    - name: Make
      run: export PATH=/home/runner/go/bin/:$PATH && make static-linux

    - name: Test
      run: ./sliver-server -unpack && ./go-tests.sh
